services:
  redis:
    image: redis:7.2
    container_name: tx-oracle-redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redisdata:/data
    command: [ "redis-server" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:14
    container_name: tx-oracle-postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
volumes:
  postgresdata:
    driver: local
  redisdata:
    driver: local
